/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 27-Jul-2024 11:04:38 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS public.budgetstandardhistory CASCADE
;

/* Create Tables */

CREATE TABLE public.budgetstandardhistory
(
	"ID" integer NOT NULL,
	item integer NULL,
	lifestyle integer NULL,
	retirementtype integer NULL,
	budgetperweek double precision NULL,
	category integer NULL,
	startdate date NULL,
	enddate date NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE public.budgetstandardhistory ADD CONSTRAINT budgetstandardhistory_pkey
	PRIMARY KEY ("ID")
;
